Update owasp-dependency-check: 4.0.2 -> 5.0.0
see https://github.com/jeremylong/DependencyCheck/issues/1558

This heals

org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz; unable to connect.
    at org.owasp.dependencycheck.utils.Downloader.fetchFile (Downloader.java:177)
    at org.owasp.dependencycheck.utils.Downloader.fetchFile (Downloader.java:93)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call (DownloadTask.java:151)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call (DownloadTask.java:43)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Error downloading file https://nvd.nist.gov/feeds/xml/cve/2.0/nvdcve-2.0-Modified.xml.gz; received response code 403.
    at org.owasp.dependencycheck.utils.Downloader.fetchFile (Downloader.java:158)
    at org.owasp.dependencycheck.utils.Downloader.fetchFile (Downloader.java:93)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call (DownloadTask.java:151)
    at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call (DownloadTask.java:43)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)